### ISSUE TITLE
java.lang.NullPointerException?

### ISSUE THREAD

**Issue by prokulit06** [VidyasagarMSC/WatBot#15]
When I try your speakerlabels this is the error that I encounter and the speaker labels is not consistent 
please help me solving this please 
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
2019-02-26 19:29:40.316 21670-21670/com.example.ezminute W/System.err:     at com.example.ezminute.activities.SpeakerLabelsDiarization$RecoTokens.cleanFinal(SpeakerLabelsDiarization.java:195)
2019-02-26 19:29:40.317 21670-21670/com.example.ezminute W/System.err:     at com.example.ezminute.activities.SpeakerLabelsDiarization$RecoTokens.add(SpeakerLabelsDiarization.java:159)
2019-02-26 19:29:40.317 21670-21670/com.example.ezminute W/System.err:     at com.example.ezminute.activities.SpeakerLabelsDiarization$RecoTokens.add(SpeakerLabelsDiarization.java:122)
2019-02-26 19:29:40.317 21670-21670/com.example.ezminute W/System.err:     at com.example.ezminute.activities.convert_to_text$MicrophoneRecognizeDelegate.onTranscription(convert_to_text.java:482)
2019-02-26 19:29:40.318 21670-21670/com.example.ezminute W/System.err:     at com.ibm.watson.developer_cloud.speech_to_text.v1.websocket.SpeechToTextWebSocketListener.onMessage(SpeechToTextWebSocketListener.java:133)
2019-02-26 19:29:40.318 21670-21670/com.example.ezminute W/System.err:     at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:322)
2019-02-26 19:29:40.319 21670-21670/com.example.ezminute W/System.err:     at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
2019-02-26 19:29:40.319 21670-21670/com.example.ezminute W/System.err:     at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
2019-02-26 19:29:40.320 21670-21670/com.example.ezminute W/System.err:     at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273)
2019-02-26 19:29:40.321 21670-21670/com.example.ezminute W/System.err:     at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:213)
2019-02-26 19:29:40.322 21670-21670/com.example.ezminute W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
2019-02-26 19:29:40.322 21670-21670/com.example.ezminute W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
2019-02-26 19:29:40.322 21670-21670/com.example.ezminute W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2019-02-26 19:29:40.323 21670-21670/com.example.ezminute W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2019-02-26 19:29:40.323 21670-21670/com.example.ezminute W/System.err:     at java.lang.Thread.run(Thread.java:764)

**Comment by prokulit06** [comment]
please help sir

**Comment by prokulit06** [comment]
please i am begging to you sir please help me

**Comment by prokulit06** [comment]
sir help me please sir

**Comment by VidyasagarMSC** [comment]
@prokulit06 Which Android API level are you trying this code on?
